### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by robertdenton** [rgpages/election-2016-general#1]
- Should this just be done in Tarbell? How would we minify CSS & JS? Ease of data in a spreadsheet could outweigh splitting up duties between Grunt and Tarbell.
- Does Grunt build just get you minified CSS/JS?
  - No, also gets jslinting and processing of HTML templates, multi js files
- If so, could data be baked using this process? Is that even necessary?
  - No
- How does data come in?
  - Photos - http://sandbox.registerguard.com/electionssp/
  - Top percent - `<iframe id="attn" src="attn.html" width="100%" height="0" marginheight="0" marginwidth="0" frameborder="0" scrolling="no"></iframe>` >>> http://projects.registerguard.com/ballot/json/topset/
  - Latest news - [registerguard.com/csp/cms/sites/rg/feeds/json.csp?items=20&subcats=elections...](http://registerguard.com/csp/cms/sites/rg/feeds/json.csp?items=20&subcats=elections%20eug-spfld%20results,%20elections%20lane%20county%20results,%20elections%20region%20results,%20elections%20oregon%20results,%20elections%20national%20results)
  - Recent coverage - http://registerguard.com/csp/cms/sites/rg/feeds/json.csp?items=20&subcats=elections,%20politics
  - From the wire - [[ http://projects.registerguard.com/ballot/json/ap_elex_stories/10/ ]]
  - Results - Example: http://projects.registerguard.com/ballot/json/eugspr/

**Comment by jheasly** [comment]
I made feeds (I'm pretty sure they're JSON) for the election results.

**Comment by robertdenton** [comment]
Some answers for next time:
- Does not need to be in Tarbell, but could be simplified
- Data cannot be baked in this process but @jheasly has method of getting data from state using [Selenium](http://docs.seleniumhq.org/) and baking out to JSON, then putting up in the same bucket
